### ISSUE TITLE
PublishContext should inherit from Subscription

### ISSUE THREAD

**Issue by mitar** [kadirahq/fast-render#159] opened 2016-02-27 12:41 UTC
Because now is trying to mock Subscription, but not everything is there. Like `_session`, `_subscriptionId`, `_idFilter` and so on. I have quite some packages which extend publish handlers and use those internal values which will now not work inside SSR. Now, one option is that I manually make all of them work, or we just fix `PublishContext` to be more compatible with normal subscription.

**Comment by mitar** [comment] 2016-02-27 12:41
See the issue which lead me to this: https://github.com/peerlibrary/meteor-reactive-publish/issues/7

**Comment by arunoda** [comment] 2016-02-27 12:54
Yeah. That's a good idea,
Could you send me a PR. I'm happy to take this in.

You can get the Subscription class from here: https://github.com/meteorhacks/meteorx

**Comment by mitar** [comment] 2016-02-27 19:02
Hm, the issue is that it is not enough just to extend it, but one should also configure all fields correctly. Not sure if this is doable. Like where to get session information.

**Comment by arunoda** [comment] 2016-02-28 01:30
Okay. That's a big project. Anyway, is there anyway we can build packages like yours without using those internals. If we can have a set of stuff we use, I think I can do something.

**Comment by mitar** [comment] 2016-02-28 07:35
I think I found a way.

**Comment by arunoda** [comment] 2016-02-28 07:56
Awesome. Keep me posted.

**Comment by mitar** [comment] 2016-02-28 08:15
See #160.

**Comment by arunoda** [comment] 2016-03-01 13:51
Hope we can close this and I merged @mitar's PR.

**Closed by arunoda** 2016-03-01 13:51 UTC

**Comment by SachaG** [comment] 2016-03-02 00:45
Does this mean the issue is also fixed for FlowRouter SSR? Or just Fast Render for now?

**Comment by arunoda** [comment] 2016-03-03 02:55
Just the FastRender. I'll do a release today.

**Comment by arunoda** [comment] 2016-03-03 03:08
@SachaG published a new version of FlowRouter SSR.
